#!/bin/bash

echo -e 'HTTP/1.1 200 OK'
echo -e 'Content-Type: text/html\r\n\r\n'

echo '<!DOCTYPE html>'
echo '<html lang="en">'
echo '<head>'
echo '    <meta charset="UTF-8">'
echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">'
echo '    <style>'
echo '        html, body {'
echo '            height: 100%;'
echo '            margin: 0;'
echo '            font-family: "Montserrat", sans-serif;'
echo '            font-size: 15px;'
echo '            line-height: 1.6;'
echo '            display: flex;'
echo '            flex-direction: column;'
echo '            align-items: center;'
echo '            background-color: #f4f4f4;'
echo '            color: #333;'
echo '        }'
echo '        .banner {'
echo '            flex: 1;'
echo '            width: 100%;'
echo '            padding: 20px;'
echo '            box-sizing: border-box;'
echo '            background-color: #fff;'
echo '            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);'
echo '            margin-top: 80px;'
echo '            max-width: 800px;'
echo '            margin-bottom: 20px;'
echo '        }'
echo '        .header {'
echo '            width: 100%;'
echo '            padding: 10px 0;'
echo '            position: fixed;'
echo '            top: 0;'
echo '            left: 0;'
echo '            right: 0;'
echo '            z-index: 1000;'
echo '            background-color: #1C300DCC;'
echo '            color: #fff;'
echo '            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);'
echo '        }'
echo '        .header_container {'
echo '            display: flex;'
echo '            justify-content: space-between;'
echo '            align-items: center;'
echo '            font-weight: 700;'
echo '            font-size: 24px;'
echo '            text-transform: uppercase;'
echo '            max-width: 800px;'
echo '            margin: 0 auto;'
echo '        }'
echo '        .nav {'
echo '            font-size: 18px;'
echo '        }'
echo '        .nav_link {'
echo '            margin: 0 15px;'
echo '            color: #ddd;'
echo '            text-decoration: none;'
echo '            transition: color 0.2s;'
echo '        }'
echo '        .nav_link:hover {'
echo '            color: #fff;'
echo '        }'
echo '        footer {'
echo '            width: 100%;'
echo '            padding: 10px 0;'
echo '            background-color: #1C300DCC;'
echo '            color: #fff;'
echo '            text-align: center;'
echo '            position: fixed;'
echo '            bottom: 0;'
echo '            left: 0;'
echo '            right: 0;'
echo '        }'
echo '        .banner h3, .banner h4 {'
echo '            color: #1C300D;'
echo '        }'
echo '        .banner pre {'
echo '            background-color: #f4f4f4;'
echo '            padding: 10px;'
echo '            border: 1px solid #ddd;'
echo '            border-radius: 5px;'
echo '            overflow: auto;'
echo '        }'
echo '    </style>'
echo '    <title>Calendar and Date Information</title>'
echo '</head>'
echo '<body>'

echo '<header class="header">'
echo '    <div class="header_container">'
echo '        <a class="nav_link" href="index.html">Cats Army</a>'
echo '        <nav class="nav">'
echo '            <a class="nav_link" href="/">About US</a>'
echo '            <a class="nav_link" href="/">JOIN US</a>'
echo '            <a class="nav_link" href="/docs">DOCS</a>'
echo '            <a class="nav_link" href="/cgi-bin">CGI</a>'
echo '            <a class="nav_link" href="/">confidential</a>'
echo '        </nav>'
echo '    </div>'
echo '</header>'

echo '<div class="banner">'

echo '    <h3>Date:</h3>'
echo '    <pre class="date-output">'
date
date -u
echo '    </pre>'

echo '    <h4>Days have passed since the beginning of the year:</h4>'
echo '    <pre class="days-output">'
date +%j
echo '    </pre>'
echo '</div>'

echo '<footer>'
echo '    <p><span class="highlight">&#169; 2024 by WebServ thabeck- matcardo</span></p>'
echo '</footer>'

echo '</body>'
echo '</html>'
